In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F 
import torch.optim as optim 

In [2]:
# 현재 실습하고 있는 파이썬 코드 재실행 해도 다음에도 같은 결과가 나오도록 랜덤 시드 설정 
torch.manual_seed(1)

In [3]:
# 실습을 위한 기본 셋팅 작업 완료 
# 훈련 데이터 x_train y_train 을 선언 

x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

# x_train 와 shape 출력
print("x_train , x_train_shape")
print(x_train)
print(x_train.size()) # or x_trian.shape

# x_train 값 x_trian size = 3x1 

print("")
# y_train and y_train shape output 
print("y_train , y_train_shape")
print(y_train)
print(y_train.shape)

# y_train 값  y_trian size = 3x1

x_train , x_train_shape
tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])

y_train , y_train_shape
tensor([[2.],
        [4.],
        [6.]])
torch.Size([3, 1])


In [4]:
# 가중치와 편향의 초기화 
# 선형희귀란 학습 데이터와 가장 잘 맞는 하나의 직선을 찾는 일입니다.
# 그리고 가장 잘 맞는 직선을 정의하는 것은 바로 W and b 입니다.
# 선형희귀의 목표는 가장 잘 마즌 직선을 정의하는 W and b 입니다.

# 가중치 0으로 초기화하고 이 값을 출력 편향 b도 0으로 초기화
# requires_grad = True -> 학습을 통해 계속. 값이 변경되는 변수임을 의미합니다 
w = torch.zeros(1, requires_grad = True) 
print("가중치 w  : ", w)  

b = torch.zeros(1, requires_grad = True)
print("편향 b : ", b)

# W 와 b 둘다 0 이므로 현 직선의 방정식 다음과 같습니다.
# 현재의 가중치 : y = 0 * x + 0 
# 지금 상태에선 x에 어떤 값이 들어가도 가설은 0을 예측하게 됩니다. 즉 아직 적절한 W와 b의 값이 아닙니다.


가중치 w  :  tensor([0.], requires_grad=True)
편향 b :  tensor([0.], requires_grad=True)


In [5]:
# 가설 세우기 
# 파이토치 코드 상으로 직선의 방정식에 해당되는 가설을 선언
hypothesis = x_train * w + b 
print("가설 : \n" , hypothesis)

가설 : 
 tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


In [6]:
# loss fn 선언 하기 
# 평균 제곱 오차를 선언
loss =torch.mean((hypothesis - y_train) ** 2)
print(loss) 

tensor(18.6667, grad_fn=<MeanBackward0>)


In [7]:
# 경사 하강법 구현 하기 
# input w b 가 sgd 의 입력이 됩니다.
optimizer = optim.SGD([w, b] , lr = 0.01)

# SGD -> 경사 하강법의 일종입니다.


In [8]:
# 기울기 0으로 초기화 
optimizer.zero_grad()

# loss fn 미분하여 기울기 계산
loss.backward()

# w 와 b 값을 업데이트
optimizer.step()

# 학습을 진행 
epoch_num = 2000 # 원하는 만큼 경사 하강법을 반복 

# epoch : 전체 훈련 데이터가 학습에 한 번 사용된 주기를 말합니다.
for epoch in range(epoch_num + 1):
    
    # Hypothesis 가설 계산
    hypothesis = x_train * w + b 
    
    # loss 계산
    loss = torch.mean((hypothesis - y_train) ** 2)
    
    # loss H(x) 개선
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    
    # 100번 마다 print Epoch w b loss 
    if epoch % 100 == 0 :
        print("Epoch {:4d}/{} W : {:.3f}, b : {:.3f} loss : {:.6f}"
              .format(epoch , epoch_num, w.item(), b.item(), loss.item()))


Epoch    0/2000 W : 0.353, b : 0.151 loss : 14.770963
Epoch  100/2000 W : 1.746, b : 0.577 loss : 0.047939
Epoch  200/2000 W : 1.801, b : 0.453 loss : 0.029624
Epoch  300/2000 W : 1.843, b : 0.356 loss : 0.018306
Epoch  400/2000 W : 1.877, b : 0.280 loss : 0.011312
Epoch  500/2000 W : 1.903, b : 0.220 loss : 0.006990
Epoch  600/2000 W : 1.924, b : 0.173 loss : 0.004319
Epoch  700/2000 W : 1.940, b : 0.136 loss : 0.002669
Epoch  800/2000 W : 1.953, b : 0.107 loss : 0.001649
Epoch  900/2000 W : 1.963, b : 0.084 loss : 0.001019
Epoch 1000/2000 W : 1.971, b : 0.066 loss : 0.000630
Epoch 1100/2000 W : 1.977, b : 0.052 loss : 0.000389
Epoch 1200/2000 W : 1.982, b : 0.041 loss : 0.000240
Epoch 1300/2000 W : 1.986, b : 0.032 loss : 0.000149
Epoch 1400/2000 W : 1.989, b : 0.025 loss : 0.000092
Epoch 1500/2000 W : 1.991, b : 0.020 loss : 0.000057
Epoch 1600/2000 W : 1.993, b : 0.016 loss : 0.000035
Epoch 1700/2000 W : 1.995, b : 0.012 loss : 0.000022
Epoch 1800/2000 W : 1.996, b : 0.010 loss : 0

In [9]:
# 결과
"""
최종 훈련 결과를 보면 최적의 기울기 W는 2에 가깝고, b는 0에 가까운 것을 볼 수 있습니다.
현재 훈련 데이터가 x_train은 [[1], [2], [3]]이고 y_train은 [[2], [4], [6]]인 것을 감안하면
실제 정답은 W가 2이고, b가 0인 H(x)=2x이므로 거의 정답을 찾은 셈입니다.
"""

'\n최종 훈련 결과를 보면 최적의 기울기 W는 2에 가깝고, b는 0에 가까운 것을 볼 수 있습니다.\n현재 훈련 데이터가 x_train은 [[1], [2], [3]]이고 y_train은 [[2], [4], [6]]인 것을 감안하면\n실제 정답은 W가 2이고, b가 0인 H(x)=2x이므로 거의 정답을 찾은 셈입니다.\n'