In [10]:
# torch.manual_seed() 하는 이유
# 결론 : 사용한 프로그램의 결과는 다른 컴퓨터에서 실행시켜도 동일한 결과를 얻을 수 있습니다.
# 이유 : torch.manual_seed()는 난수 발생 순서와 값을 동일하게 보장해주는 특징 

import torch
torch.manual_seed(3)
print("Random seed is 3")

# range (start , end) -> 출력 범위 지정 
for i in range(1,3):
    print(torch.rand(1))

Random seed is 3
tensor([0.0043])
tensor([0.1056])


In [16]:
torch.manual_seed(3)
print("Random seed is 5")

for i in range(1,3):
    print(torch.rand(1))

Random seed is 5
tensor([0.0043])
tensor([0.1056])
