In [1]:
# 파이토치 텐서 선언하기 

# 파이토치는 Numpy와 매우 유사합니다 

import torch
# 1. 1D with pyTorch
# 1차원 백터를 선언 
t_torch = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print("1D with pyTorch test print : ", t_torch)


1D with pyTorch test print :  tensor([0., 1., 2., 3., 4., 5., 6.])


In [2]:
# pyTorch 현재 텐서의 차원을 보는법 
print("pyTorch 텐서 차원 info")
print(t_torch.dim()) # rank 즉 차원 
print(t_torch.shape) # shape 
print(t_torch.size()) # shape 


pyTorch 텐서 차원 info
1
torch.Size([7])
torch.Size([7])


In [3]:
# 1차원 텐서 , 원소는 7개 / 인덱스 접근 과 슬라이싱 실습 
print("pyTorch 텐서 인덱스 접근")
print(t_torch[0] , t_torch[1], t_torch[-1]) # 인덱스 접근 t[-1] -> 뒤에서 인덱스 접근 즉 ) [0. 1. 2.] 출력은 2.0 (맨 뒤부터 인덱스 접근)

print("")
print("pyTorch  슬라이싱")
# [0. 1. 2. 3. 4. 5. 6.]
# start 2 index - end 5 index / start 4 index end -1 (맨뒤 인덱스 첫번째)
print(t_torch[2:5] , t_torch[4:-1])

pyTorch 텐서 인덱스 접근
tensor(0.) tensor(1.) tensor(6.)

pyTorch  슬라이싱
tensor([2., 3., 4.]) tensor([4., 5.])


In [4]:
# 2D with PyTorch 
t_2d_pyTorch = torch.FloatTensor([[1., 2., 3.],
                                   [4., 5., 6.],
                                   [7., 8., 9.],
                                   [10., 11., 12.]
                                 ])

print("2D with pyTorch test print : \n", t_2d_pyTorch)

2D with pyTorch test print : 
 tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [5]:
# 2D info 
print("pyTorch 텐서 차원 info")
print(t_2d_pyTorch.dim())
print(t_2d_pyTorch.size())
print(t_2d_pyTorch.shape)

pyTorch 텐서 차원 info
2
torch.Size([4, 3])
torch.Size([4, 3])


In [6]:
# 2차원 텐서 슬라이싱 
print("2차원 텐서 인덱스 슬라이싱")
print(t_2d_pyTorch[:,0])  # 첫번째 차원을 전체 선택한 상황에서 두번째 차원의 첫번째 것만 가져옴
print(t_2d_pyTorch[:,0].size()) # 슬라이싱 한 텐서 size 알고 싶은경우 
print("")

# 만약 맨 첫번째 차원을 선택한 상황에서 두번째 차원에서는 맨 마지막에서 첫번째를 제외하고 다 가져오고 싶은경우 
print(t_2d_pyTorch[:, :-1])

2차원 텐서 인덱스 슬라이싱
tensor([ 1.,  4.,  7., 10.])
torch.Size([4])

tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


In [7]:
# 브로드 캐스팅 
"""
두 행렬 A, B가 있다고 해봅시다. 행렬의 덧셈과 뺄셈에 대해 알고계신다면, 
이 덧셈과 뺄셈을 할 때에는 두 행렬 A, B의 크기가 같아야한다는 것을 알고계실겁니다. 
그리고 두 행렬이 곱셈을 할 때에는 A의 마지막 차원과 B의 첫번째 차원이 일치해야합니다.

물론, 이런 규칙들이 있지만 딥 러닝을 하게되면 불가피하게 크기가 다른 행렬 또는 텐서에 대해서 사칙 연산을 수행할 필요가 있는 경우가 생깁니다. 
이를 위해 파이토치에서는 자동으로 크기를 맞춰서 연산을 수행하게 만드는 브로드캐스팅이라는 기능을 제공합니다.
"""

m1 = torch.FloatTensor([[3,3]])
m2 = torch.FloatTensor([[2,2]])

print(m1 + m2)
print("")
# m1 m2 크기는 둘다 (1,2)
print("m1, m2 size info print code")
print("print m1 size = " , m1.size())
print("print m2 size = " , m2.size())

tensor([[5., 5.]])

m1, m2 size info print code
print m1 size =  torch.Size([1, 2])
print m2 size =  torch.Size([1, 2])


In [8]:
# 브로드 캐스팅 실습 
# Vector + scalar 물론 수학적으로는 원래 연산이 안 되는게 맞지만 파이토치에서는 브로드캐스팅 통해 이를 연산합니다.
m3 = torch.FloatTensor([[1,2]])
m4 = torch.FloatTensor([3]) # [3] -> [3,3]

print(m3 + m4)
print("")
print("m3, m4 size info print code")
print("print m3 size = " , m3.size())
print("print m4 size = " , m4.size())

# pyTorch는 m4 size (1,2) 로 변경해서 연산을 수행합니다.

tensor([[4., 5.]])

m3, m4 size info print code
print m3 size =  torch.Size([1, 2])
print m4 size =  torch.Size([1])


In [9]:
# 2x1 Vector + 1x2 Vector

m5 = torch.FloatTensor([[1,2]])
m6 = torch.FloatTensor(([[3], [4]]))
print(m5 + m6)
print("")
print("m5, m6 size info print code")
print("print m5 size = " , m5.size())
print("print m6 size = " , m6.size())

# m5 크기는 (1,2) m6 크기는 (2,1) 이 두 벡터는 원래 수학적으로 덧셈을 수행 불가능 그러나 파이토치는 두 백터의 크기를 (2,2)로 변경하여 덧셈 수행

# 브로드 캐스팅 과정 
# [1,2]
# ===> [[1,2],
#       [1,2]]
# [3]
# [4]
# ===> [[3,3], 
#       [4,4]]

# 단 주의사항 
# 브로드캐스팅은 편리하지만, 자동으로 실행되는 기능이므로 사용자 입장에서는 굉장히 주의해서 사용해야합니다
"""
A텐서와 B텐서가 있는데 사용자는 이 두 텐서의 크기가 같다고 착각하고 덧셈 연산을 수행했다고 가정하면 
하지만 실제로 이 두 텐서의 크기는 달랐고 브로드캐스팅이 수행되어 덧셈 연산이 수행되었습니다.
만약 두 텐서의 크기가 다르다고 에러를 발생했다면 사용자는 이 연산이 잘못되었음을 알 수 있지만 브로드 캐스팅으로 진행하면 자동으로 변경되다보니
사용자는 나중에 원하는 결과가 나오지 않았더라도 어디서 문제가 발생했는지 찾기가 굉장히 어려울 수 있습니다.
"""


tensor([[4., 5.],
        [5., 6.]])

m5, m6 size info print code
print m5 size =  torch.Size([1, 2])
print m6 size =  torch.Size([2, 1])


'\nA텐서와 B텐서가 있는데 사용자는 이 두 텐서의 크기가 같다고 착각하고 덧셈 연산을 수행했다고 가정하면 \n하지만 실제로 이 두 텐서의 크기는 달랐고 브로드캐스팅이 수행되어 덧셈 연산이 수행되었습니다.\n만약 두 텐서의 크기가 다르다고 에러를 발생했다면 사용자는 이 연산이 잘못되었음을 알 수 있지만 브로드 캐스팅으로 진행하면 자동으로 변경되다보니\n사용자는 나중에 원하는 결과가 나오지 않았더라도 어디서 문제가 발생했는지 찾기가 굉장히 어려울 수 있습니다.\n'

In [10]:
# Tensor 생성 
# Tensor 생성할 때 대표적으로 사용하는 함수 rand, zeros ones 

# 랜덤 넘버 생성 
x = torch.rand(2,3)
print(x)
print("torch.FloatTensor of size" , x.size())

tensor([[0.6896, 0.9932, 0.9883],
        [0.4162, 0.3552, 0.4196]])
torch.FloatTensor of size torch.Size([2, 3])


In [11]:
# 주어진 범위 내의 정수를 랜덤하게 생성 randperm(범위)
rx = torch.torch.randperm(5)
print(rx)
print("torch.LongTensor of size" , rx.size())

tensor([2, 0, 4, 1, 3])
torch.LongTensor of size torch.Size([5])


In [12]:
# 모든 값이 0인 zeros tensor 를 생성
zx = torch.zeros(2,3 , dtype=torch.long) # dtype=torch.long 원하는 타입을 선언가능
print(zx)

tensor([[0, 0, 0],
        [0, 0, 0]])


In [13]:
# 1인 ones Tensor 생성 
ox = torch.ones(2,3)
print(ox)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [14]:
# torch.arange(start,end,step=1) -> [start,end) with step
# 시작 / 끝 / 단계 을 인자로 사용하여 시작은 이상 끝은 미만의 범위를 가지고 단계 만큼 간격을 두고 Tensor 생성

ax = torch.arange(0, 3 , step = 0.5)
print(ax)

tensor([0.0000, 0.5000, 1.0000, 1.5000, 2.0000, 2.5000])


In [15]:
# 초기화 되지 않은 5x3 행렬 생성 
# 초기화되지 않은 행렬이 선언되었지만 사용하기 전에는 명확히 알려진 값을 포함하고 있지는 않습니다.
# 즉 초기화되지 않은 행렬이 생성되면 그 시점에 할당된 메모리에 존재하던 값들이 초기값으로 나타납니다.

ex = torch.empty(5,3)
print(ex)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
